name: build-esp32s2

on:
  workflow_dispatch:
    inputs:
      git-address:
        description: 'git-address'
        required: true
        default: 'https://github.com/adafruit/circuitpython'
      branches-tags:
        description: 'branches-tags'
        required: true
        default: '7.0.0-beta.0'
      board:
        description: 'board'
        required: true
        default: 'espressif_saola_1_wrover'
      custom-board:
        description: 'custom-board'
        required: false
        default: ''
      build-with:
        description: 'build-with'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Clone source code
      run: |
        git clone --recursive ${{github.event.inputs.git-address}} /opt/circuitpython
        cd /opt/circuitpython

    - name: Install packages
      run: |
        brew install cmake
        sudo apt install ninja-build cmake
        sudo apt install python-is-python3
        sudo apt-get install gettext
        cd /opt/circuitpython
        git checkout ${{github.event.inputs.branches-tags}}
        git pull origin ${{github.event.inputs.branches-tags}}
        git submodule update --init
        cd /opt/circuitpython/ports/esp32s2
        ./esp-idf/install.sh

    - name: Bulid
      run: |
        cd /opt/circuitpython/ports/esp32s2
        source ./esp-idf/export.sh
        mkdir /opt/firmware
        cd /opt/circuitpython
        cp -r /home/runner/work/circuitpython-actions/circuitpython-actions/boards/${{github.event.inputs.custom-board}} ports/esp32s2/boards
        cd /opt/circuitpython/ports/esp32s2
        make BOARD=${{github.event.inputs.board}} ${{github.event.inputs.build-with}}
        cp /opt/circuitpython/ports/esp32s2/build-${{github.event.inputs.board}}/firmware.bin /opt/firmware
        cp /opt/circuitpython/ports/esp32s2/build-${{github.event.inputs.board}}/firmware.uf2 /opt/firmware

    - name : Upload firmware-${{github.event.inputs.branches-tags}}-esp32s2-${{github.event.inputs.board}}
      uses: actions/upload-artifact@master
      with:
        name: firmware-${{github.event.inputs.branches-tags}}-esp32s2-${{github.event.inputs.board}}
        path: /opt/firmware
